server:
    port: 8097
spring:
    datasource:
        password: user
        url: jdbc:postgresql://localhost:5432/orm_customer
        username: postgres
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: classpath:liquibase/changelog-master.yml
        enabled: true
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest

client:
    accounts:
        url: http://localhost:8096/accounts

queue:
    mail-sender-q: Mail_Sender_Q