server:
    port: 8096
spring:
    datasource:
        password: user
        url: jdbc:postgresql://localhost:5432/orm_account
        username: postgres
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: liquibase/changelog-master.yml
        enabled: true
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest

client:
    customers:
        url: http://localhost:8097/customers

queue:
    mail-sender-q: Mail_Sender_Q